const meta = {"fundamentals-course": {"image": "assets/prog-fundamentals.jpg", "alt": "Two members practising a standing no-gi drill", "href": "training/beginners/"}, "beginners": {"image": "assets/private-coaching.jpg", "alt": "A coach guiding a student through a jiu-jitsu drill", "href": "training/beginners/"}, "all-levels": {"image": "assets/prog-gi.jpg", "alt": "Gi class training at the Queenstown academy", "href": "training/adults/"}, "advanced": {"image": "assets/competition.jpg", "alt": "Experienced members training jiu-jitsu", "href": "training/adults/"}, "womens": {"image": "assets/women-rolling-2.jpeg", "alt": "Two women practising jiu-jitsu on the mats", "href": "training/womens/"}, "kids": {"image": "assets/prog-kids.jpg", "alt": "Two children practising jiu-jitsu together on the mats", "href": "training/kids/"}};
export const featuredClassDefaults = [{"_key": "class-fundamentals-course", "_type": "featuredClass", "key": "fundamentals-course", "name": "Fundamentals Course", "subtitle": "6-week introduction", "description": "A structured introduction to the basics of jiu-jitsu, with time to build confidence before joining regular classes."}, {"_key": "class-beginners", "_type": "featuredClass", "key": "beginners", "name": "Beginners", "subtitle": "white belts & new starters", "description": "Learn the core positions and movements at a pace made for people starting out."}, {"_key": "class-all-levels", "_type": "featuredClass", "key": "all-levels", "name": "All-levels", "subtitle": "all belts welcome", "description": "Technique, drilling and live training with room for every level of experience."}, {"_key": "class-advanced", "_type": "featuredClass", "key": "advanced", "name": "Advanced", "subtitle": "higher-level technique", "description": "Build on your foundations with more detailed technique and live training."}, {"_key": "class-womens", "_type": "featuredClass", "key": "womens", "name": "Women’s", "subtitle": "dedicated women’s class", "description": "A dedicated space for women to learn, train and find their place on the mats."}, {"_key": "class-kids", "_type": "featuredClass", "key": "kids", "name": "Kids", "subtitle": "ages 5–12", "description": "Games, movement and technique that build focus and confidence in a safe class."}];
export const featuredClassOptions = featuredClassDefaults.map(item => ({title:item.name,value:item.key}));
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
// CMS refreshes replace these rows after the scroll observer has registered.
// Render them visible so delayed content never leaves invisible, clickable links.
export function renderFeaturedClasses(items) {
  if (!Array.isArray(items) || !items.length) return null;
  return items.filter(item => meta[item?.key]).map(item => {
    const {image,alt,href} = meta[item.key];
    return `<div class="prog reveal in"><a href="${href}"><h3>${escape(item.name)}<span class="pt">${escape(item.subtitle)}</span></h3><span class="tag">${escape(item.subtitle)}</span><img class="prog-img" src="${image}" alt="${escape(alt)}" loading="lazy"><p>${escape(item.description)}</p></a></div>`;
  }).join('');
}
