import {imageURL} from './shared.js';
export const postsQuery='*[_type == "post" && defined(slug.current)] | order(publishedAt desc){_id,title,slug,category,excerpt,publishedAt,cover,body}';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const validSlug=value=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value||'');
export const postPath=post=>'/blog/'+post.slug.current+'/';
export const dateLabel=value=>Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('en-NZ',{day:'numeric',month:'long',year:'numeric',timeZone:'Pacific/Auckland'}).format(new Date(value)):'';
const safeLink=value=>typeof value==='string' && (/^https?:\/\//i.test(value)||/^mailto:[^\s]+$/i.test(value))?value:null;
export function renderBody(blocks,config){
 let html='',list=null;
 const close=()=>{if(list){html+='</'+list+'>';list=null;}};
 for(const block of blocks||[]){
  if(block._type==='image'){close();const url=imageURL(block,config);if(url)html+='<figure><img src="'+escapeHTML(url)+'" alt="'+escapeHTML(block.alt)+'" loading="lazy">'+(block.caption?'<figcaption>'+escapeHTML(block.caption)+'</figcaption>':'')+'</figure>';continue;}
  if(block._type!=='block')continue;
  const text=(block.children||[]).map(span=>{let value=escapeHTML(span.text).replace(/\n/g,'<br>');for(const mark of span.marks||[]){if(['strong','em'].includes(mark))value='<'+mark+'>'+value+'</'+mark+'>';else{const def=block.markDefs?.find(d=>d._key===mark);const url=safeLink(def?.href);if(url)value='<a href="'+escapeHTML(url)+'" rel="noopener noreferrer">'+value+'</a>';}}return value;}).join('');
  const next=block.listItem==='bullet'?'ul':block.listItem==='number'?'ol':null;
  if(next){if(list!==next){close();list=next;html+='<'+next+'>';}html+='<li>'+text+'</li>';}
  else{close();const tag=['h2','h3','blockquote'].includes(block.style)?block.style:'p';html+='<'+tag+'>'+text+'</'+tag+'>';}
 }close();return html;
}
export function renderPostCards(posts,config,home=false){
 if(!posts.length)return '<p class="blog-empty">'+(home?'Stories from the academy will appear here soon.':'No articles published yet. Check back soon.')+'</p>';
 return posts.map((p,i)=>{const url=imageURL(p.cover,config);return '<article class="'+(home?'post':'journal-card'+(i===0?' journal-card--feature':''))+'">'+(url?'<'+(home?'div class="post-img"':'figure')+'><img style="width:100%;height:100%;object-fit:cover" src="'+escapeHTML(url)+'" alt="'+escapeHTML(p.cover.alt)+'" loading="lazy"></'+(home?'div':'figure')+'>':'')+'<div class="'+(home?'post-body':'journal-card-body')+'"><div class="journal-meta"><span class="post-tag">'+escapeHTML(p.category)+'</span> <span class="post-date">'+dateLabel(p.publishedAt)+'</span></div><h3><a href="'+postPath(p)+'">'+escapeHTML(p.title)+'</a></h3><p>'+escapeHTML(p.excerpt)+'</p><a class="post-more" href="'+postPath(p)+'" aria-label="Read '+escapeHTML(p.title)+'">Read article &rarr;</a></div></article>';}).join('');
}
export function renderPostPage(post,config){
 const e=escapeHTML,url=imageURL(post.cover,config),back=post.category==='Technique'?'/seminars/technique/':'/seminars/news/';
 return '<!doctype html><html lang="en-NZ"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+e(post.title)+' | Carlson Gracie NZ</title><meta name="description" content="'+e(post.excerpt)+'"><meta property="og:type" content="article"><meta property="og:title" content="'+e(post.title)+'"><meta property="og:description" content="'+e(post.excerpt)+'">'+(url?'<meta property="og:image" content="'+e(url)+'">':'')+'<style>'+articleCSS+'</style></head><body><header class="masthead"><a href="/">CARLSON GRACIE <span>NEW ZEALAND</span></a><a href="'+back+'">Back to '+e(post.category)+' &rarr;</a></header><main><article><div class="intro"><p class="eyebrow">'+e(post.category)+' · '+dateLabel(post.publishedAt)+'</p><h1>'+e(post.title)+'</h1><p class="summary">'+e(post.excerpt)+'</p></div>'+(url?'<figure class="cover"><img src="'+e(url)+'" alt="'+e(post.cover.alt)+'"></figure>':'')+'<div class="article-body">'+renderBody(post.body,config)+'</div></article><footer><a href="'+back+'">&larr; More '+e(post.category.toLowerCase())+'</a><a href="/membership/trial/">Try a class &rarr;</a></footer></main></body></html>';
}
const articleCSS=`*{box-sizing:border-box}body{margin:0;background:#f5f3ee;color:#17171b;font-family:Arial,sans-serif}a{color:inherit;text-underline-offset:4px}a:focus-visible{outline:3px solid #b82930;outline-offset:5px}.masthead{padding:24px clamp(20px,5vw,80px);background:#17171b;color:white;display:flex;justify-content:space-between;gap:24px;align-items:center}.masthead a{text-decoration:none;font-size:13px;font-weight:700;letter-spacing:.07em}.masthead span{display:block;font-size:10px;margin-top:5px;font-weight:400}main{max-width:1160px;margin:auto;padding:64px 24px}.intro{max-width:820px;margin:0 auto 40px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.15em;line-height:1.8;color:#8d292b}h1{font-family:Georgia,serif;font-weight:400;font-size:clamp(36px,6vw,72px);line-height:1.08;letter-spacing:-.03em;margin:20px 0;overflow-wrap:anywhere}.summary{font-size:21px;line-height:1.65;color:#565659}.cover{margin:0 0 56px}.cover img{width:100%;max-height:650px;object-fit:cover}.article-body{max-width:720px;margin:auto;font-size:18px;line-height:1.85;overflow-wrap:anywhere}.article-body h2,.article-body h3{font-family:Georgia,serif;line-height:1.2;margin-top:2em}.article-body h2{font-size:34px}.article-body h3{font-size:27px}.article-body figure{margin:40px 0}.article-body img{width:100%;height:auto}figcaption{font-size:14px;color:#666}blockquote{border-left:3px solid #a22e31;padding-left:24px;margin:32px 0;font-style:italic}footer{margin:64px auto 0;padding-top:28px;border-top:1px solid #ccc;max-width:720px;display:flex;justify-content:space-between;gap:20px}@media(max-width:600px){main{padding-top:36px}.masthead{padding:20px}.masthead a{font-size:11px}.summary{font-size:18px}.article-body{font-size:17px}}`;
